apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name:  db-user-provider-rolebinding
subjects:
  - kind: ServiceAccount
    name:  db-user-provider-sa
    namespace: db-user-provider
roleRef:
  kind: ClusterRole
  name:  db-user-provider-role
  apiGroup: rbac.authorization.k8s.io